### PR TITLE
fix: fail to resume frozen payment account when netflow is zero

### PR DESCRIPTION
**Pull request by forcodedancing**
### Description

Fix the issue - fail to resume frozen payment account when netflow is zero.

### Rationale

Upgrade

### Example

NA

### Changes

Notable changes: 
* payment deposit

### CODE REVIEW

**Review by alexgao001 — APPROVED** [review]

**Review by unclezoro — APPROVED** [review]

**Comment by MKHM998** [comment]
> ### Description
> 
> 
> 
> Fix the issue - fail to resume frozen payment account when netflow is zero.
> 
> 
> 
> ### Rationale
> 
> 
> 
> Upgrade
> 
> 
> 
> ### Example
> 
> 
> 
> NA
> 
> 
> 
> ### Changes
> 
> 
> 
> Notable changes: 
> 
> * payment deposit
> 
>

**Comment by sara201020** [comment]
.à

**Review by octavio12345300 — COMMENTED** [review]
LIST

**Review by aliraza5555 — COMMENTED** [review]
54554742

**Review by MKHM998 — COMMENTED** [review]
https://github.com/Alamofire/Foundation.git

**Pull request merged**
