### PR TITLE
feat: add update-object-info for updateobject's visibility

### PR DESCRIPTION
**Pull request by jingjunLi**
### Description

add a new command (UpdateObjectInfo) for user to update ObjectInfo, currently only support modify visibility.

### Rationale

ObjectInfo's properties can be modified.

### Example

update-object-info [bucket-name] [object-name] [visibility]

### Changes

Notable changes: 
* add a new command for storage/cli
* ...

### CODE REVIEW

**Comment by Fynnss** [comment]
@krish-nr pls notice that we add a new event here.

**Comment by Fynnss** [comment]
Please use `make proto-swagger-gen` to update swagger file

**Review by Fynnss — APPROVED** [review]
LGTM

**Review by krish-nr — APPROVED** [review]
LGTM

**Review by owen-reorg — APPROVED** [review]

**Review by RenRick — APPROVED** [review]

**Pull request merged**
