### PR TITLE
feat: limit sp slash amount and add query api

### PR DESCRIPTION
**Pull request by forcodedancing**
### Description

This pr will update challenge module for the following changes:
* limit the slash total amount for single sp during some period
* return challenge id when submitting challenge
* add query api for query result of single attested challenge - the result will be cleaned

### Rationale

new features

### Example

na

### Changes

Notable changes: 
* limit the total slash amount for a sp

### CODE REVIEW

**Comment by forcodedancing** [comment]
Had run `make proto-swagger-gen` and it shows no changes locally.

**Comment by Fynnss** [comment]
> Had run `make proto-swagger-gen` and it shows no changes locally.

ensure the version is the same as the CI

```
which swagger-combine || npm install -g swagger-combine
which protoc-gen-swagger || go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

2 packages are looking for funding
  run `npm fund` for details
v1.4.0
1.25.0
```

**Comment by forcodedancing** [comment]
> > Had run `make proto-swagger-gen` and it shows no changes locally.
> 
> ensure the version is the same as the CI
> 
> ```
> which swagger-combine || npm install -g swagger-combine
> which protoc-gen-swagger || go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
> 
> 2 packages are looking for funding
>   run `npm fund` for details
> v1.4.0
> 1.25.0
> ```

It seems that I am using newer versions.
```
make proto-swagger-gen  
/Users/liguo/.nvm/versions/node/v14.20.1/bin/swagger-combine
/Users/liguo/go/bin/protoc-gen-swagger
v1.4.0
1.13.1
```

**Comment by forcodedancing** [comment]
Wait e2e test case fix in https://github.com/bnb-chain/greenfield/pull/371

**Pull request merged**
